FROM dustinsoftware/rpi-percona
MAINTAINER rawdlite@gmail.com
ADD my.cnf /etc/my.cnf 
ADD init_rompr_db.sh /docker-entrypoint-initdb.d/init_rompr_db.sh
RUN chmod u+x /docker-entrypoint-initdb.d/init_rompr_db.sh
